In [1]:
import numpy as np 

In [3]:
arreglo_once_cuadrado = np.arange(11)**2

In [4]:
arreglo_once_cuadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
arreglo_once_cuadrado[0]

0

In [6]:
arreglo_once_cuadrado[0:3]

array([0, 1, 4], dtype=int32)

In [7]:
arreglo_once_cuadrado[-1]

100

In [8]:
arreglo_once_cuadrado[-5:-1]

array([36, 49, 64, 81], dtype=int32)

In [9]:
arreglo_once_cuadrado[-5:9]

array([36, 49, 64], dtype=int32)

In [10]:
arreglo_once_cuadrado[3:]

array([  9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
arreglo_once_cuadrado[-6:]

array([ 25,  36,  49,  64,  81, 100], dtype=int32)

In [12]:
arreglo_once_cuadrado[:2]

array([0, 1], dtype=int32)

In [13]:
arreglo_once_cuadrado[:-6]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [16]:
arreglo_once_cuadrado[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [17]:
arreglo_once_cuadrado[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
arreglo_once_cuadrado[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [19]:
for numero in arreglo_once_cuadrado[::-1]:
    print(numero)

100
81
64
49
36
25
16
9
4
1
0
