In [3]:
import numpy as np

In [43]:
arreglo1 = np.array([[2,4],[6,8]])
arreglo1

array([[2, 4],
       [6, 8]])

In [48]:
arreglo_zeros = np.zeros([2,2], dtype = int)
arreglo_zeros

arreglo_unos = np.ones([2,2], dtype = int)
arreglo_unos

array([[1, 1],
       [1, 1]])

In [50]:
# La funcion add suma los arrays seleccionados
suma = np.add(arreglo1,arreglo_unos)
print("Suma de dos arrays: ")
print(suma)

Suma de dos arrays: 
[[3 5]
 [7 9]]


In [52]:
# La funcion eye nos da una matriz identidad con la diagonal con 1s
arreglo_identidad = np.eye(4, dtype=int)
arreglo_identidad

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [53]:
# La funcion 'sum' suma los elementos del arraya seleccionado
suma_elementos_matriz = np.sum(arreglo_identidad)
print("\nSuma de los elementos de un array: ")
print(suma_elementos_matriz)


Suma de los elementos de un array: 
4


In [41]:
# La funcion dot es el producto punto de dos matrices
a = [[2,0],[0,2]]
b = [[1,4],[2,2]]
producto = np.dot(a,b)
producto

array([[2, 8],
       [4, 4]])

In [37]:
print(a)
print(b)

[[2, 0], [0, 2]]
[[1, 4], [2, 2]]


In [12]:
# [Primer intervalo],[Fin del intervalo],[separacion entre valores]
a =  np.arange(1,17,3)
a

array([ 1,  4,  7, 10, 13, 16])

In [13]:
a.shape

(6,)

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
a.reshape((3,2))

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])