In [1]:
import numpy as np

In [4]:
array1 = np.array([[2,4],[6,8]])
array1

array([[2, 4],
       [6, 8]])

In [6]:
array2 = np.array([[1,3],[5,7]])
array2

array([[1, 3],
       [5, 7]])

In [17]:
# La funcion add suma los arrays seleccionados
suma = np.add(array1,array2)
print("Suma de dos arrays: ")
print(suma)

Suma de dos arrays: 
[[ 3  7]
 [11 15]]


In [18]:
# la funcion 'sum' suma los elementos del arraya seleccionado
suma1 = np.sum(array1)
print("\nSuma de los elementos de un array: ")
print(suma1)


Suma de los elementos de un array: 
20
