In [1]:
import numpy as np

In [43]:
arreglo1 = np.array([[2,4],[6,8]])
arreglo1

array([[2, 4],
       [6, 8]])

In [48]:
arreglo_zeros = np.zeros([2,2], dtype = int)
arreglo_zeros

arreglo_unos = np.ones([2,2], dtype = int)
arreglo_unos

array([[1, 1],
       [1, 1]])

In [50]:
# La funcion add suma los arrays seleccionados
suma = np.add(arreglo1,arreglo_unos)
print("Suma de dos arrays: ")
print(suma)

Suma de dos arrays: 
[[3 5]
 [7 9]]


In [52]:
# La funcion eye nos da una matriz identidad con la diagonal con 1s
arreglo_identidad = np.eye(4, dtype=int)
arreglo_identidad

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [53]:
# La funcion 'sum' suma los elementos del arraya seleccionado
suma_elementos_matriz = np.sum(arreglo_identidad)
print("\nSuma de los elementos de un array: ")
print(suma_elementos_matriz)


Suma de los elementos de un array: 
4


In [41]:
# La funcion dot es el producto punto de dos matrices
a = [[2,0],[0,2]]
b = [[1,4],[2,2]]
producto = np.dot(a,b)
producto

array([[2, 8],
       [4, 4]])

In [37]:
print(a)
print(b)

[[2, 0], [0, 2]]
[[1, 4], [2, 2]]


In [38]:
a = np.arange(3*4*5*6)

In [39]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [42]:
np.zeros(3)

array([0., 0., 0.])